app = "rapla-ical-proxy"
primary_region = "arn"

[build]
image = "ghcr.io/satoqz/rapla-ical-proxy"

[http_service]
processes = ["app"]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = "shared-cpu-1x"
